### ISSUE TITLE
MCP_Counter does not produce output 

### ISSUE THREAD

**Issue by SynatKeam** [ebecht/MCPcounter#26] opened 2021-10-17 14:44 UTC
Dear author, 

Hope you are doing great. I had just tried MCP counter in R today and did not suceed with it.

Basically, I had normalized count_matrix from DESEq2 and the normalized count is also log2 tranformed with ENSEMBL_ID as in attach. 

I used MCP.estiamte as shown in the attach. I tried two options. However, I alwasy got 0 * 0 matrix when I run it. Could you help me examine it whether what was the issue with it. I am quite interested to estimate the immune and the two stromal cells (endothelial cells and Fibroblast). I am wondering whether you could help check it and I really appreciated.

Looking forward to hearing your response. 

Kind Regards,

Synat, 
![Count_Matrix](https://user-images.githubusercontent.com/86950372/137632320-a93aede1-51fd-499e-8643-0164b2d47370.JPG)
![R_Code](https://user-images.githubusercontent.com/86950372/137632324-5c6d043a-d992-4f99-9a77-bfc83715d5f3.JPG)

**Comment by SynatKeam** [comment] 2021-10-17 14:45
I would like to add that the sample is from mouse tumour tissue. 

Kind Regards,

Synat

**Comment by ebecht** [comment] 2021-10-17 17:36
Hi @SynatKeam 

This is likely because there is no overlap between your rownames and the genes used in MCPcounter. That is because MCPcounter is designed for human, but @FPetitprez developped a version for mouse: you can download it [here](https://github.com/cit-bioinfo/mMCP-counter)

Also I noted there are negative values and -Inf in your expression matrix, that is likely due to applying some logtransform without applying a pseudocount. You may consider adding a fixed value (e.g. 1) to your expression matrix before applying the log transformation.

Best,
Etienne

**Comment by SynatKeam** [comment] 2021-10-18 00:45
Dear Eitenne,

Thank for your quick response. I will try it today and let you know soon whether it is working or not. 

I really appreciated for your help and have a nice day!

Kind Regards,

synat

**Comment by SynatKeam** [comment] 2021-10-18 09:35
Dear Etienne, 

Thank for your help today. I could make it to work. However, I had a bit of final question I like to ask. 
Do you think whether I have done it correctly by normalizing the data first then doing log2 transformation with pseudocount? or I can just apply the log2 transformation to the unnormalized data? which way is correct? 

Kind Regards,

synat

**Comment by ebecht** [comment] 2021-10-18 09:49
Glad to hear it worked

I think you did it correctly: DESeq2 should be applied to the count matrix, and then you can log-transform the normalized counts.

Best,
Etienne

**Comment by SynatKeam** [comment] 2021-10-18 09:53
Thanks for the help. 
As you are the expert in this area. Sorry to insert another question. Do you happen to know whether we can estimate the level of cytokines from abundance of Bulk RNAseq in addition to the fraction of immune cells. Sorry the question is a bit out of topic, but I have been searching for many day, but could not find any package or web-interface. After this, you can close the issue. If I have any further question, I will ask. Really appreciate for helping me.

Kind Regards,

Synat,

**Comment by ebecht** [comment] 2021-10-18 10:05
You're very welcome.

I don't know any tool that can do what you are asking sadly! It sounds like a difficult question. The naive way to approach this is to use the transcripts but in many instances these will not correlate with the amount of soluble cytokines sadly.

I'm closing this since the issue is solved!

Etienne

**Closed as completed by ebecht** 2021-10-18 10:05 UTC
