### ISSUE TITLE
question about test data GSE64385

### ISSUE THREAD

**Issue by kkamiii** [ebecht/MCPcounter#21] opened 2020-11-07 11:35 UTC
Hello!

I have downloaded GSE64385.RAW.tar file from GEO site and processed data using oligo package in R
But, when I tried MCPcounter.estimate(GSE64385.expression.matrix, featuresType="ENTREZ_ID") , I got this output
![ddd](https://user-images.githubusercontent.com/72592400/98439920-851baa00-2138-11eb-904d-3aaf67ee1080.PNG)
![wd](https://user-images.githubusercontent.com/72592400/98439921-86e56d80-2138-11eb-9175-eb5865452f05.PNG)

I think that I miss-used code so the output is wrong..
Can you please answer me how to get accurate results??

**Comment by ebecht** [comment] 2020-11-07 15:25
Hi @kkamiii 

Why do you think the results are wrong? They don't look particularly bad to me? What would the issue be?

**Comment by kkamiii** [comment] 2020-11-08 02:09
Thank you for answering 👍 

This data is in vitro RNA mixture so I know what is real percentage
Particularly the column 1 and column 2 is HCT116 colon cancer cell lines' expression data.
I think that all value should be equal to 0 because it don't have other cell except cancer cell.
or..could the output be interpreted differently?

**Comment by ebecht** [comment] 2020-11-08 12:58
For microarrays you have quite a lot of "background" fluorescence signal, so even genes that are not expressed will show some non-0 measurement.

In this case you can see that the first two columns are much lower for all the scores than the other mixtures.

In our paper we used these negative controls to assess MCP-counter's limit of detection.

I think everything's working as intended in this case. Remember to not interpret the score absolutely, but rather compare across your samples. You can think of them as "metagenes".

I'll close the issue since there is no problem.

**Closed as completed by ebecht** 2020-11-08 12:58 UTC
